// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmjgWMOc0pTaFu8JwWqOTVRa8ki0r1bEU',
    appId: '1:233321347526:web:f8f7e0b40a5a39b0749ac7',
    messagingSenderId: '233321347526',
    projectId: 'amacle-manager-developer-app',
    authDomain: 'amacle-manager-developer-app.firebaseapp.com',
    storageBucket: 'amacle-manager-developer-app.appspot.com',
    measurementId: 'G-Z23ZM4FY8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiuVAHFL5qxKKX0hM4og_oe4ODdr2vneA',
    appId: '1:233321347526:android:fdd6fd22fa4b5946749ac7',
    messagingSenderId: '233321347526',
    projectId: 'amacle-manager-developer-app',
    storageBucket: 'amacle-manager-developer-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkyLTQBQN5aEdvBpqvEhAOF0SXkKhkLuU',
    appId: '1:233321347526:ios:c0d67285b3043ab0749ac7',
    messagingSenderId: '233321347526',
    projectId: 'amacle-manager-developer-app',
    storageBucket: 'amacle-manager-developer-app.appspot.com',
    androidClientId: '233321347526-n8emmlfhffkusm36n33rb5qn36qvi87t.apps.googleusercontent.com',
    iosClientId: '233321347526-4cnodnl2ikrmuer3q0dfdt42t2mpjmt9.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientAppAmacleStudio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkyLTQBQN5aEdvBpqvEhAOF0SXkKhkLuU',
    appId: '1:233321347526:ios:b416522776a23c49749ac7',
    messagingSenderId: '233321347526',
    projectId: 'amacle-manager-developer-app',
    storageBucket: 'amacle-manager-developer-app.appspot.com',
    androidClientId: '233321347526-n8emmlfhffkusm36n33rb5qn36qvi87t.apps.googleusercontent.com',
    iosClientId: '233321347526-qit54neagr2cghbtobobspuikcg08sur.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientAppAmacleStudio.RunnerTests',
  );
}
